# Generated by Django 5.2.17 on 2026-09-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="idea_title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
